version: '3'

vars:
  CONTAINER_NAME: some-postgres

dotenv: ['.env']

tasks:
  run-postgres:
    cmds:
      - |
        docker run \
        --name {{.CONTAINER_NAME}} \
        -p {{.POSTGRES_PORT}}:5432 \
        -e POSTGRES_USER={{.POSTGRES_USER}} \
        -e POSTGRES_PASSWORD={{.POSTGRES_PASSWORD}} \
        -e POSTGRES_DB={{.POSTGRES_DB}} \
        -d postgres

  rm-postgres:
    cmds:
      - docker rm -f {{.CONTAINER_NAME}}

  psql:
    cmds:
      - psql --host=localhost --username={{.POSTGRES_USER}} -p {{.POSTGRES_PORT}} {{.POSTGRES_DB}}

  run-main:
    cmds:
      - go run main.go
