version: '3'

tasks:
  proto:
    desc: Generate code from proto files.
    cmds:
      - |
        protoc \
        --proto_path=internal/controller/grpc/v1/ \
        --go_out=. \
        --go_opt=module=github.com/sudeeya/avito-assignment \
        --go-grpc_out=. \
        --go-grpc_opt=module=github.com/sudeeya/avito-assignment \
        internal/controller/grpc/v1/pvz.proto

  rebuild:
    desc: Rebuild services.
    cmds:
      - docker compose build

  up:
    desc: Create and start containers.
    cmds:
      - docker compose up

  down:
    desc: Stop and remove containers, networks.
    cmds:
      - docker compose down

  integration:
    desc: Run integration tests.
    cmds:
      - docker compose up --wait
      - go test -count 1 -v ./tests/integration/...
      - docker compose down
